### ISSUE TITLE
Infractions Ideas

### ISSUE THREAD

**Issue by gvanzin-allegheny** [gvanzin-allegheny/code-of-conduct#2]
This is the paragraph I wrote so far for the infractions; are there any other I should include?

Infractions are the punishments handed out to those who break the rules or don't follow class conduct one or more times.  The more that the class conduct is broken by the individual, the more severe the penalty is.  The different infractions are cheating, not respecting others or the instructor, and breaking equipment.

**Comment by lukel43** [comment]
You might want to add something about refusal to contribute to team efforts as well. Other than that it looks great!

**Comment by gvanzin-allegheny** [comment]
Infractions are the punishments handed out to those who break the rules or don't follow class conduct one or more times. The more that the class conduct is broken by the individual, the more severe the penalty is. The different infractions are cheating, not respecting others or the instructor, breaking equipment, and refusal to contribute to team efforts.

This is the new paragraph.

**Comment by gvanzin-allegheny** [comment]
Infractions are the punishments handed out to those who break the rules or don't follow class conduct one or more times. The more that the class conduct is broken by the individual, the more severe the penalty is. Infractions are split upon different categories and each infraction category adds to a point total when committed.  For example, if you commit three Level 1 infractions, that is just the same as committing 1 Level 2 infraction.  The higher the total infraction points you have, the worse the punishment is.

The final paragraph I believe.
