### ISSUE TITLE
The Different Levels of Infractions

### ISSUE THREAD

**Issue by Yanqiao4396** [gvanzin-allegheny/code-of-conduct#3]
Try to category the infractions. For different levels, there are some the examples of violations and the reactions professors give to them.

**Comment by gvanzin-allegheny** [comment]
I think these 4 would work,

1. Cheating, 
2. Not respecting others or the instructor, 
3. Breaking equipment
4. Refusal to contribute to team efforts.

Each one should have a different penalty and perhaps a way to resolve the infraction.

For example, cheating results in 0% grade, cheating three times results in honor code stuff.
Or, apology to the person you disrespected results in no penalty if they forgive you?

Ya know?

**Comment by lukel43** [comment]
> I think these 4 would work,
> 
> 1. Cheating,
> 2. Not respecting others or the instructor,
> 3. Breaking equipment
> 4. Refusal to contribute to team efforts.
> 
> Each one should have a different penalty and perhaps a way to resolve the infraction.
> 
> For example, cheating results in 0% grade, cheating three times results in honor code stuff. Or, apology to the person you disrespected results in no penalty if they forgive you?
> 
> Ya know?

Perhaps 2. and 4. could be combined as such:

2. Not respecting others or instructor (refusal to complete work)

This would keep us at 3 bullet points to keep formatting consistent, but this topic is a bit different than the others so we may need to use a different format all together. Let me know what you think!

**Comment by gvanzin-allegheny** [comment]
That sounds good, so the 3 would be these:

1. Cheating
2. Not respecting others or instructor (refusal to complete work)
3. Breaking Equipment Purposefully
