### ISSUE TITLE
Appeal process and determining when infractions occur

### ISSUE THREAD

**Issue by lukel43** [gvanzin-allegheny/code-of-conduct#8]
As a group we seem to have run into an issue when determining what the punishments should be. We would like to establish some standards around what defines an infraction and the process around determining, and delivering punishments. Firstly, we have the issue of there needing to be an authority to determine when an infraction occurs. Currently, our best solution is to allow both the professor and TLs to determine when infractions occur. Additionally, if you disagree with this decision, you can appeal with either the professor or a TL, who would then have the authority to make a decision. 

While this solution seems natural for a classroom setting and easy to implement. I have concerns that this solution could nullify the power of the code of conduct and working out conflicts amongst ourselves.

Please, feel free to point out any additional issues you may see, or offer solutions that may be better than the current one. Thank you!

**Comment by mariakimheinert** [comment]
Hi @lukel43! Thanks for creating this issue to discuss this important topic of appeals.

May I ask for some clarification on these specific statements you made?

> Firstly, we have the issue of there needing to be an authority to determine when an infraction occurs. Currently, our best solution is to allow both the professor and TLs to determine when infractions occur.

Does this mean that the instructor and TLs will be responsible for detecting infractions or will students be able to report infractions?

> Additionally, if you disagree with this decision, you can appeal with either the professor or a TL, who would then have the authority to make a decision.

The conduct guide should be specific about who exactly must make the final decision. I think either allowing the instructor to make the final decision or requiring there to be a majority, or even a unanimous, vote among the instructor and TLs would both be acceptable. What do you think?

**Comment by lukel43** [comment]
Absolutely, thank you for you comments! 

To address your statements:

> > Firstly, we have the issue of there needing to be an authority to determine when an infraction occurs. Currently, our best solution is to allow both the professor and TLs to determine when infractions occur.
> 
> Does this mean that the instructor and TLs will be responsible for detecting infractions or will students be able to report infractions?

I feel it would be best to allow anyone in the class (instructor and TLs included) to report the infraction. As long as we all agree on a reasonable process to judge these infractions, and there are clear limitations to the severity of the punishments that are outlined in the rest of the code of conduct, to prevent report spam or abuse. Again I would love more feedback as to how this could be implemented or improved!

> > Additionally, if you disagree with this decision, you can appeal with either the professor or a TL, who would then have the authority to make a decision.
> 
> The conduct guide should be specific about who exactly must make the final decision. I think either allowing the instructor to make the final decision or requiring there to be a majority, or even a unanimous, vote among the instructor and TLs would both be acceptable. What do you think?

I think either idea would work, but perhaps a weighted vote where voting power is divided as follows could be optimal:

Instructor: 33%
TLs: 33%
Students: 33%

Also, the vote could be only used at certain levels of infractions, and left up to the instructor or TLs for lower level infractions in order to prevent constant voting. Feel free to suggest different percentages or a better system in general, and let me know if I can clarify anything further! Thanks!

**Comment by mariakimheinert** [comment]
Hi @lukel43!

I think it is a good idea to allow anyone in the class to report an infraction.

The issue with a weighted vote that involves students is that some infractions are best kept private between the students involved and the instructor. So, I would be more in favor of an appeal process that does not involve students or possibly even TLs. Additionally, I am in favor of keeping this appeal process as simple as possible. So, it would be best not to have different appeal processes for each level of infraction. What do you think of a policy where the appeal is made only to the instructor and the instructor can make the final decision?

**Comment by Yanqiao4396** [comment]
I feel so good about all the ideas above. 
To me, I feel like we can give students right to choose if they want TLs to get involved, except for the extreme cases which may involve other participants' rights of privacy.
What do you think?

**Comment by mariakimheinert** [comment]
@Yanqiao4396, you raise a good point that maybe some students will want to involve TLs in the appeal process. However, what if one student involved in the conflict wants to involve TLs and another student does not? Because these types of complicated situations could occur, I would still recommend that infraction appeals should be handled only by the instructor.

**Comment by Yanqiao4396** [comment]
@mariakimheinert  Thanks for reminder. I forgot to consider the particularity of this class. As a software engineering class, the interactions among people account a lot. We always need to work with others. In this case, after noticing the truth, I agree on the idea that appeal should be handled only be the instructor, because infraction involves more than one person is hard to be minor case.
